const app = document.querySelector('#app');
const socket = io();
let state = { role: null, session: null, question: null, answered: false, results: null };
const esc = (value) => String(value ?? '').replace(/[&<>'"]/g, (c) => ({ '&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;' })[c]);
const participantUrl = (code) => `${location.origin}${location.pathname}?join=${code}`;
const participantCount = () => state.session?.participants ?? 0;
function layout(content) { app.innerHTML = `<nav class="nav"><div class="brand">pulse<span>.</span></div><div class="tag">Realtime polling for teams</div></nav><div class="wrap">${content}</div>`; }
function home() { layout(`<section class="hero"><div class="eyebrow">Live polls & quizzes</div><h1>Every voice,<br>in the room.</h1><p>Run fast, friendly live questions. Your team joins with a six-digit code — no downloads and no built-in attendee ceiling.</p><div class="actions"><button class="btn" id="create">Create a session</button><button class="btn secondary" id="show-join">Join a session</button></div></section><section id="join-slot"></section>`); document.querySelector('#create').onclick = createScreen; document.querySelector('#show-join').onclick = joinScreen; }
function createScreen() { layout(`<div class="card" style="max-width:780px;margin:auto"><div class="eyebrow">Host setup</div><h1 class="screen-title" style="font-size:38px">Build your live session</h1><form id="create-form"><div class="field"><label>Session title</label><input name="title" value="Friday team pulse" maxlength="80" required></div><div id="editors"></div><button type="button" class="btn secondary" id="add-question">+ Add question</button><button class="btn" style="float:right">Create session</button></form></div>`); const editors = document.querySelector('#editors');
  const add = () => { const index = editors.children.length + 1; const block = document.createElement('div'); block.className = 'question-editor'; block.innerHTML = `<div class="field"><label>Question ${index}</label><input class="qtext" placeholder="What would you like to ask?" required></div><div class="options"><input class="option" placeholder="Option 1" required><input class="option" placeholder="Option 2" required><input class="option" placeholder="Option 3 (optional)"><input class="option" placeholder="Option 4 (optional)"></div><label class="notice"><input class="quiz-mode" type="checkbox"> This is a scored quiz question</label><div class="field correct-slot hidden"><label>Correct option number (1–4)</label><input class="correct-option" type="number" min="1" max="4" placeholder="e.g. 2"></div>`; block.querySelector('.quiz-mode').onchange = (event) => block.querySelector('.correct-slot').classList.toggle('hidden', !event.target.checked); editors.append(block); }; add(); document.querySelector('#add-question').onclick = add;
  document.querySelector('#create-form').onsubmit = async (e) => { e.preventDefault(); const questions = [...editors.children].map((el) => ({ text: el.querySelector('.qtext').value, options: [...el.querySelectorAll('.option')].map((input) => input.value), correctOptionId: el.querySelector('.quiz-mode').checked ? String(Math.max(0, Number(el.querySelector('.correct-option').value || 1) - 1)) : undefined })); const response = await fetch('/api/sessions', { method: 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify({ title: new FormData(e.currentTarget).get('title'), questions }) }); const data = await response.json(); if (!response.ok) return alert(data.error); state = { role:'host', session:data, question:null, answered:false, results:null }; socket.emit('host:join', { code:data.code }, hostScreen); };
}
function joinScreen() { const slot = document.querySelector('#join-slot') || app; slot.innerHTML = `<section class="card join"><div class="eyebrow">Join live</div><h1 class="screen-title" style="font-size:37px">Enter the room</h1><form id="join-form"><div class="field"><label>Session code</label><input name="code" inputmode="numeric" maxlength="6" placeholder="123456" required></div><div class="field"><label>Your name</label><input name="name" maxlength="32" placeholder="e.g. Riya" required></div><button class="btn">Join session</button></form></section>`; document.querySelector('#join-form').onsubmit = (e) => { e.preventDefault(); const data = Object.fromEntries(new FormData(e.currentTarget)); socket.emit('participant:join', data, (reply) => { if (reply.error) return alert(reply.error); state = { role:'participant', session:reply.session, question:reply.question, answered:false, results:null }; participantScreen(); }); }; }
function hostScreen(reply) { if (reply?.error) return alert(reply.error); if (reply?.session) { state.session = reply.session; state.question = reply.question; state.results = null; } const s = state.session; const url = participantUrl(s.code); layout(`<div class="host-top"><div><div class="eyebrow">Host dashboard</div><h1 class="screen-title" style="font-size:42px">${esc(s.title)}</h1></div><div class="stats"><span class="dot"></span><span id="audience">${participantCount()} joined</span></div></div><section class="grid"><div class="card"><div class="eyebrow">Invite your team</div><div class="code">${s.code}</div><p class="notice">Ask everyone to visit this link, or enter the session code.</p><div class="linkbox"><span>${esc(url)}</span><button class="btn secondary" id="copy">Copy</button></div></div><div class="card" id="host-stage"></div></section>`); document.querySelector('#copy').onclick = () => navigator.clipboard.writeText(url); renderHostStage(); }
function renderHostStage() { const stage = document.querySelector('#host-stage'); if (!stage) return; const s = state.session; if (s.status === 'lobby') stage.innerHTML = `<div class="eyebrow">Ready when you are</div><h2>Start the first question</h2><p class="notice">${s.questionCount} question${s.questionCount > 1 ? 's' : ''} prepared. Participants can join at any time.</p><button class="btn" id="start">Start session</button>`; else if (s.status === 'question') stage.innerHTML = `<div class="eyebrow">Question ${s.questionIndex + 1} of ${s.questionCount}</div><h2>${esc(state.question?.text)}</h2><p class="notice"><strong id="answer-count">${state.question?.totalAnswers ?? 0}</strong> answers received</p><button class="btn" id="close">Close answers</button>`; else if (s.status === 'results') stage.innerHTML = `<div class="eyebrow">Results revealed</div><h2>See how the room answered</h2><p class="notice">The participant view now shows the live leaderboard.</p><button class="btn" id="next">${s.questionIndex + 1 === s.questionCount ? 'Finish session' : 'Next question'}</button>`; else stage.innerHTML = `<div class="eyebrow">Session complete</div><h2>That’s a wrap.</h2><p class="notice">Thanks for bringing everyone into the conversation.</p>`;
  document.querySelector('#start')?.addEventListener('click', () => socket.emit('host:start')); document.querySelector('#close')?.addEventListener('click', () => socket.emit('host:close')); document.querySelector('#next')?.addEventListener('click', () => socket.emit('host:next'));
}
function participantScreen() { const q = state.question; if (!q && state.session.status === 'lobby') return layout(`<section class="card join"><div class="eyebrow">You’re in</div><h1 class="screen-title" style="font-size:42px">Welcome to ${esc(state.session.title)}</h1><p class="notice">The host will start the first question shortly.</p></section>`); if (state.results) return resultsScreen(); layout(`<section class="stage"><div class="eyebrow">${esc(state.session.title)} · Question ${state.session.questionIndex + 1} of ${state.session.questionCount}</div><h1 class="question">${esc(q.text)}</h1><div class="choices">${q.options.map((option) => `<button class="choice ${state.answered ? 'selected':''}" data-option="${option.id}" ${state.answered ? 'disabled':''}>${esc(option.text)}</button>`).join('')}</div><p class="notice" style="margin-top:24px">${state.answered ? 'Answer received — wait for the results.' : 'Choose one answer.'}</p></section>`); document.querySelectorAll('[data-option]').forEach((button) => button.onclick = () => socket.emit('participant:answer', { optionId:button.dataset.option }, (reply) => { if (reply.error) return alert(reply.error); state.answered = true; participantScreen(); })); }
function resultsScreen() { const { counts, question, leaderboard: board } = state.results; const total = Math.max(1, Object.values(counts).reduce((a,b) => a+b, 0)); layout(`<section class="stage"><div class="eyebrow">Results</div><h1 class="question">${esc(question.text)}</h1><div class="card" style="text-align:left">${question.options.map((o) => { const n = counts[o.id] || 0; return `<div class="result"><div><strong>${esc(o.text)}</strong><div class="bar" style="width:${Math.round(n / total * 100)}%"></div></div><strong>${Math.round(n / total * 100)}%</strong></div>`; }).join('')}</div><div class="leader"><h3>Live leaderboard</h3>${board.map((p,i) => `<div class="rank"><span>${i + 1}. ${esc(p.name)}</span><span>${p.score} pts</span></div>`).join('') || '<p class="notice">No scores yet.</p>'}</div><p class="notice">Waiting for the host to continue…</p></section>`); }
socket.on('session:stats', (s) => { state.session = { ...state.session, ...s }; document.querySelector('#audience') && (document.querySelector('#audience').textContent = `${s.participants} joined`); if (state.role === 'host') renderHostStage(); });
socket.on('question:open', (question) => { state.question = question; state.results = null; state.answered = false; if (state.role === 'host') hostScreen(); else participantScreen(); });
socket.on('question:progress', ({ totalAnswers }) => { if (state.question) state.question.totalAnswers = totalAnswers; document.querySelector('#answer-count') && (document.querySelector('#answer-count').textContent = totalAnswers); });
socket.on('question:results', (results) => { state.results = results; state.session.status = 'results'; if (state.role === 'host') hostScreen(); else resultsScreen(); });
socket.on('session:complete', ({ leaderboard }) => { state.session.status = 'complete'; if (state.role === 'host') hostScreen(); else { state.results = { ...(state.results || { question:{ text:'Session complete', options:[] }, counts:{} }), leaderboard }; resultsScreen(); } });
const codeParam = new URLSearchParams(location.search).get('join'); if (codeParam) { home(); joinScreen(); document.querySelector('[name=code]').value = codeParam; } else home();
