const app = document.querySelector('#app');
const socket = io();
const storedParticipant = (() => { try { return JSON.parse(sessionStorage.getItem('pulseParticipant') || 'null'); } catch { return null; } })();
let state = { role: null, session: null, question: null, answered: false, results: null, participant: storedParticipant, lastAnswer: null, leaderboard: null, hostToken: null };
const esc = (value) => String(value ?? '').replace(/[&<>'"]/g, (c) => ({ '&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;' })[c]);
const participantUrl = (code) => `${location.origin}${location.pathname}?join=${code}`;
const hostUrl = (code, token) => `${location.origin}${location.pathname}?host=${code}&token=${encodeURIComponent(token)}`;
const participantCount = () => state.session?.participants ?? 0;
function layout(content) { app.innerHTML = `<nav class="nav"><div class="brand">pulse<span>.</span></div><div class="tag">Realtime polling for teams</div></nav><div class="wrap">${content}</div>`; }
function home() { layout(`<section class="hero"><div class="eyebrow">Live polls & quizzes</div><h1>Every voice,<br>in the room.</h1><p>Run fast, friendly live questions. Your team joins with a six-digit code — built for large live groups.</p><div class="actions"><button class="btn" id="create">Create a session</button><button class="btn secondary" id="show-join">Join as participant</button><button class="btn secondary" id="show-host">Join as host</button></div></section><section id="join-slot"></section>`); document.querySelector('#create').onclick = createScreen; document.querySelector('#show-join').onclick = joinScreen; document.querySelector('#show-host').onclick = hostJoinScreen; }
function createScreen() { layout(`<div class="card" style="max-width:780px;margin:auto"><div class="eyebrow">Host setup</div><h1 class="screen-title" style="font-size:38px">Build your live quiz</h1><form id="create-form"><div class="field"><label>Session title</label><input name="title" value="Friday team quiz" maxlength="80" required></div><div id="editors"></div><button type="button" class="btn secondary" id="add-question">+ Add question</button><button class="btn" style="float:right">Create session</button></form></div>`); const editors = document.querySelector('#editors');
  const add = () => { const index = editors.children.length + 1; const block = document.createElement('div'); block.className = 'question-editor'; block.innerHTML = `<div class="field"><label>Question ${index}</label><input class="qtext" placeholder="What would you like to ask?" required></div><div class="options"><input class="option" placeholder="Option 1" required><input class="option" placeholder="Option 2" required><input class="option" placeholder="Option 3 (optional)"><input class="option" placeholder="Option 4 (optional)"></div><label class="notice quiz-toggle"><input class="quiz-mode" type="checkbox" checked> Scored quiz question</label><div class="field correct-slot"><label>Correct option number (1–4)</label><input class="correct-option" type="number" min="1" max="4" placeholder="e.g. 2" value="1"></div>`; block.querySelector('.quiz-mode').onchange = (event) => block.querySelector('.correct-slot').classList.toggle('hidden', !event.target.checked); editors.append(block); }; add(); document.querySelector('#add-question').onclick = add;
  document.querySelector('#create-form').onsubmit = async (e) => { e.preventDefault(); const questions = [...editors.children].map((el) => ({ text: el.querySelector('.qtext').value, options: [...el.querySelectorAll('.option')].map((input) => input.value), correctOptionId: el.querySelector('.quiz-mode').checked ? String(Math.max(0, Number(el.querySelector('.correct-option').value || 1) - 1)) : undefined })); const response = await fetch('/api/sessions', { method: 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify({ title: new FormData(e.currentTarget).get('title'), questions }) }); const data = await response.json(); if (!response.ok) return alert(data.error); state = { role:'host', session:data, question:null, answered:false, results:null, participant:null, lastAnswer:null, leaderboard:null, hostToken:data.hostToken }; socket.emit('host:join', { code:data.code, hostToken:data.hostToken }, hostScreen); };
}
function joinScreen() { const slot = document.querySelector('#join-slot') || app; slot.innerHTML = `<section class="card join"><div class="eyebrow">Join as participant</div><h1 class="screen-title" style="font-size:37px">Enter the room</h1><form id="join-form"><div class="field"><label>Session code</label><input name="code" inputmode="numeric" maxlength="6" placeholder="123456" required></div><div class="field"><label>Your name</label><input name="name" maxlength="32" placeholder="e.g. Riya" required></div><button class="btn">Join session</button></form></section>`; document.querySelector('#join-form').onsubmit = (e) => { e.preventDefault(); const data = Object.fromEntries(new FormData(e.currentTarget)); socket.emit('participant:join', data, (reply) => { if (reply.error) return alert(reply.error); state = { role:'participant', session:reply.session, question:reply.question, answered:false, results:null, participant:reply.participant, lastAnswer:null, leaderboard:reply.leaderboard, hostToken:null }; sessionStorage.setItem('pulseParticipant', JSON.stringify({ ...reply.participant, sessionCode:reply.session.code })); participantScreen(); }); }; }
function hostJoinScreen() { const slot = document.querySelector('#join-slot') || app; slot.innerHTML = `<section class="card join"><div class="eyebrow">Host access</div><h1 class="screen-title" style="font-size:37px">Open your host dashboard</h1><p class="notice">Use the host link from when you created the session. The host link is private and is different from the participant join code.</p><form id="host-join-form"><div class="field"><label>Session code</label><input name="code" inputmode="numeric" maxlength="6" placeholder="123456" required></div><div class="field"><label>Host access token</label><input name="token" placeholder="Paste your host token" required></div><button class="btn">Open host dashboard</button></form></section>`; document.querySelector('#host-join-form').onsubmit = (e) => { e.preventDefault(); const data = Object.fromEntries(new FormData(e.currentTarget)); state.hostToken = data.token; socket.emit('host:join', { code:data.code, hostToken:data.token }, hostScreen); }; }
function hostScreen(reply) { if (reply?.error) return alert(reply.error); if (reply?.session) { state.session = reply.session; state.question = reply.question; state.results = null; state.leaderboard = reply.leaderboard; } const s = state.session; const pUrl = participantUrl(s.code); const hUrl = hostUrl(s.code, state.hostToken); layout(`<div class="host-top"><div><div class="eyebrow">Host dashboard</div><h1 class="screen-title" style="font-size:42px">${esc(s.title)}</h1></div><div class="stats"><span class="dot"></span><span id="audience">${participantCount()} joined</span></div></div><section class="grid"><div class="card"><div class="eyebrow">Invite your team</div><div class="code">${s.code}</div><p class="notice">Share the participant link or six-digit code with your employees. Keep the host link private.</p><div class="field"><label>Participant link</label><div class="linkbox"><span>${esc(pUrl)}</span><button class="btn secondary" id="copy-participant">Copy</button></div></div><div class="field" style="margin-top:14px"><label>Private host link</label><div class="linkbox"><span>${esc(hUrl)}</span><button class="btn secondary" id="copy-host">Copy</button></div></div></div><div class="card" id="host-stage"></div></section>`); document.querySelector('#copy-participant').onclick = () => navigator.clipboard?.writeText(pUrl); document.querySelector('#copy-host').onclick = () => navigator.clipboard?.writeText(hUrl); renderHostStage(); }
function leaderboardMarkup(board, highlightName = null) { const top = board?.top || []; return `<div class="leader"><div class="leader-head"><h3>🏆 Leaderboard</h3><span>${board?.totalParticipants || 0} players</span></div>${top.length ? top.map((p) => `<div class="rank ${highlightName && p.name === highlightName ? 'me':''}"><span><b>${p.rank <= 3 ? ['🥇','🥈','🥉'][p.rank - 1] : `#${p.rank}`}</b> ${esc(p.name)}</span><strong>${p.score.toLocaleString()} pts</strong></div>`).join('') : '<p class="notice">No scores yet.</p>'}</div>`; }
function renderHostStage() { const stage = document.querySelector('#host-stage'); if (!stage) return; const s = state.session; if (s.status === 'lobby') stage.innerHTML = `<div class="eyebrow">Ready when you are</div><h2>Start the first question</h2><p class="notice">${s.questionCount} question${s.questionCount > 1 ? 's' : ''} prepared. Participants can join at any time.</p><button class="btn" id="start">Start quiz</button>`; else if (s.status === 'question') stage.innerHTML = `<div class="eyebrow">Question ${s.questionIndex + 1} of ${s.questionCount}</div><h2>${esc(state.question?.text)}</h2><div class="timer" id="host-timer">15</div><p class="notice"><strong id="answer-count">${state.question?.totalAnswers ?? 0}</strong> answers received</p><button class="btn" id="close">Reveal answer & leaderboard</button>`; else if (s.status === 'results') { const q = state.results?.question; stage.innerHTML = `<div class="eyebrow">Question ${s.questionIndex + 1} results</div><h2>${q ? esc(q.text) : 'Results'}</h2><p class="notice">Correct answer: <strong>${esc(q?.options.find((o) => o.id === state.results?.correctOptionId)?.text || 'Not scored')}</strong></p>${leaderboardMarkup(state.results?.leaderboard)}<button class="btn" id="next">${s.questionIndex + 1 === s.questionCount ? 'Show final podium' : 'Next question'}</button>`; } else { stage.innerHTML = `<div class="eyebrow">Session complete</div><h2>🏆 Final results</h2>${leaderboardMarkup(state.leaderboard)}`; }
  document.querySelector('#start')?.addEventListener('click', () => socket.emit('host:start')); document.querySelector('#close')?.addEventListener('click', () => socket.emit('host:close')); document.querySelector('#next')?.addEventListener('click', () => socket.emit('host:next')); if (s.status === 'question') startTimer(state.question?.startedAt, state.question?.durationMs || 15000, '#host-timer'); }
function startTimer(startedAt, durationMs, selector) { const el = document.querySelector(selector); if (!el || !startedAt) return; const tick = () => { const remaining = Math.max(0, durationMs - (Date.now() - startedAt)); el.textContent = Math.ceil(remaining / 1000); if (remaining > 0 && document.querySelector(selector) === el) requestAnimationFrame(tick); }; tick(); }
function participantScreen() { const q = state.question; if (state.session.status === 'complete') return finalParticipantScreen(); if (!q && state.session.status === 'lobby') return layout(`<section class="card join"><div class="eyebrow">You’re in</div><h1 class="screen-title" style="font-size:42px">Welcome to ${esc(state.session.title)}</h1><p class="notice">The host will start the first question shortly.</p><div class="waiting">● Waiting for the host…</div></section>`); if (state.results) return resultsScreen(); layout(`<section class="stage"><div class="eyebrow">${esc(state.session.title)} · Question ${state.session.questionIndex + 1} of ${state.session.questionCount}</div><div class="timer" id="participant-timer">15</div><h1 class="question">${esc(q.text)}</h1><div class="choices">${q.options.map((option) => `<button class="choice ${state.answered ? 'selected':''}" data-option="${option.id}" ${state.answered ? 'disabled':''}>${esc(option.text)}</button>`).join('')}</div><p class="notice" style="margin-top:24px">${state.answered ? '✓ Answer received — watch the leaderboard.' : 'Choose one answer before the timer runs out.'}</p></section>`); document.querySelectorAll('[data-option]').forEach((button) => button.onclick = () => socket.emit('participant:answer', { optionId:button.dataset.option }, (reply) => { if (reply.error) return alert(reply.error); state.answered = true; state.lastAnswer = reply; participantScreen(); })); startTimer(q.startedAt, q.durationMs || 15000, '#participant-timer'); }
function resultsScreen() { const { counts = {}, question, leaderboard: board, correctOptionId } = state.results; const total = Math.max(1, Object.values(counts).reduce((a,b) => a+b, 0)); const ownRank = board?.participantRank; const ownScore = board?.participantScore ?? state.participant?.score ?? 0; const earned = state.lastAnswer?.earnedPoints || 0; layout(`<section class="stage"><div class="eyebrow">Question ${state.session.questionIndex + 1} results</div><div class="result-hero">${state.lastAnswer?.isCorrect ? '✓ Correct!' : '✕ Not quite'}</div><p class="score-pop">${earned ? `+${earned.toLocaleString()} points` : '0 points'}</p><h1 class="question">${esc(question.text)}</h1><div class="card" style="text-align:left">${question.options.map((o) => { const n = counts[o.id] || 0; const pct = Math.round(n / total * 100); const correct = o.id === correctOptionId; return `<div class="result ${correct ? 'correct':''}"><div><strong>${correct ? '✓ ' : ''}${esc(o.text)}</strong><div class="bar" style="width:${pct}%"></div></div><strong>${pct}%</strong></div>`; }).join('')}</div>${leaderboardMarkup(board, state.participant?.name)}${ownRank ? `<div class="your-rank">Your rank: <strong>#${ownRank}</strong> · ${ownScore.toLocaleString()} pts</div>` : ''}<p class="notice">Waiting for the host to continue…</p></section>`); }
function finalParticipantScreen() { const board = state.leaderboard || state.results?.leaderboard; const ownRank = board?.participantRank; layout(`<section class="stage"><div class="eyebrow">Final results</div><h1 class="screen-title">🏆 Quiz complete</h1><p class="notice">Congratulations to everyone who played!</p>${leaderboardMarkup(board, state.participant?.name)}${ownRank ? `<div class="your-rank">Your final rank: <strong>#${ownRank}</strong> · ${(board.participantScore || 0).toLocaleString()} pts</div>` : ''}</section>`); }
socket.on('session:stats', (s) => { state.session = { ...state.session, ...s }; document.querySelector('#audience') && (document.querySelector('#audience').textContent = `${s.participants} joined`); if (state.role === 'host') renderHostStage(); });
socket.on('question:open', (question) => { state.question = question; state.results = null; state.answered = false; state.lastAnswer = null; if (state.role === 'host') hostScreen(); else participantScreen(); });
socket.on('question:progress', ({ totalAnswers }) => { if (state.question) state.question.totalAnswers = totalAnswers; document.querySelector('#answer-count') && (document.querySelector('#answer-count').textContent = totalAnswers); });
socket.on('question:results', (results) => { state.results = results; state.leaderboard = results.leaderboard; state.session.status = 'results'; if (state.role === 'host') hostScreen(); else resultsScreen(); });
socket.on('session:complete', ({ leaderboard }) => { state.session.status = 'complete'; state.leaderboard = leaderboard; if (state.role === 'host') hostScreen(); else finalParticipantScreen(); });
const params = new URLSearchParams(location.search);
const joinCode = params.get('join');
const hostCode = params.get('host');
const hostToken = params.get('token');
if (hostCode && hostToken) {
  state.role = 'host'; state.hostToken = hostToken;
  socket.emit('host:join', { code:hostCode, hostToken }, (reply) => { if (reply?.error) { home(); return alert(reply.error); } hostScreen(reply); });
} else if (joinCode) { home(); joinScreen(); document.querySelector('[name=code]').value = joinCode; } else home();
